version: '3'

services:
  web-app1:
    build: .
    ports:
      - 9000:8080
  web-app2:
    build: .
    ports:
      - 9001:8080
  nginx:
    image: nginx:latest
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      -  80:80
    depends_on:
      - web-app1
      - web-app2