version: '3'

services:
  web-app1:
    build: .
    ports:
      - 9000:9000
  web-app2:
    build: .
    ports:
      - 9001:9000
  nginx:
    build: nginx:latest
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      -  80:80
    depends_on:
      - web-app1
      - web-app2
    command: >  # remove containers
      sh -c "nginx -g 'daemon off;' && docker rmi -f $(docker images -q)"
